openapi: "3.1.0"
info:
  title: Antifraud API
  version: "0.0.1"
servers:
  - url: http://localhost

paths:
  /observation:
    get:
      summary: Начать наблюдение
      parameters:
        - name: nonce
          in: path
          required: true
          schema:
            type: string
          description: Случайное значение для алгоритма проверки легитимности Антифрода.
      responses:
        '200':
          description: ''
    head:
      summary: Дать команду "загрузить наблюдение".
      responses:
        '200':
          description: ''

components:
  schemas:
    ObservationUpload.request:
      type: object
      properties:
        observation:
          $ref: "#/components/schemas/Observation"
        nonce:
          type: string
        sig:
          $ref: "#/components/schemas/Signature"
        auth_token:
          type: string
          description: Переданный браузером токен пользователя
      required:
        - observation
        - nonce
        - sig
        - auth_token
    Signature:
      type: string
      description: Подпись легитимности (Base64). Формируется по схеме nonce || Observation
    Observation:
      type: object
      properties:
        cheated:
          type: boolean
          description: Мухлевал ли экзаменуемый при прохождении экзамена?
        violations:
          type: string
          description: Указание нарушений
      required:
        - cheated
        - violations
    ObservationUpload.response:
      type: object
      properties:
        trust_token:
          type: string
