openapi: "3.1.0"
info:
  title: Antifraud API
  version: "0.0.1"
servers:
  - url: http://localhost

paths:
  /session:
    head:
      summary: Приветственный запрос
      description: Инициализировать процесс аутентификации и начала сессии.
      responses:
        '200':
          description: ''
      security:
        - userPassedToken: [ ]

  /observation:
    head:
      summary: Дать команду "загрузить наблюдение".
      responses:
        '200':
          description: ''
        '500':
          description: Присутствуют нарушения
      security:
        - userPassedToken: [ ]

components:
  schemas:
    ObservationUpload:
      allOf:
        - $ref: "#/components/schemas/Observation"
        - type: object
          properties:
            sig:
              type: string
              description: Подпись легитимности
            checksum:
              $ref: "#/components/schemas/Checksum"
    Checksum:
      type: object
      properties:
        checksum:
          type: string
          description: Контрольная сумма бинаря Антифрода
        sig:
          type: string
          description: Подпись легитимности
    Observation:
      type: object
      properties:
        cheated:
          type: boolean
          description: Мухлевал ли экзаменуемый при прохождении экзамена?
        details:
          type: string
          description: Указание нарушений
  securitySchemes:
    userPassedToken:
      type: http
      scheme: bearer