openapi: "3.1.0"
info:
  title: Antifraud API
  version: "beta"
servers:
  - url: http://localhost

paths:
  /session:
    head:
      summary: Приветственный запрос
      description: Инициализировать процесс аутентификации и начала сессии.
      security:
        - userPassedToken: [ ]

  /observation:
    head:
      summary: Дать команду "загрузить наблюдение".
      security:
        - userPassedToken: [ ]

  /echo:
    get:
      summary: Проверить присутствие
      responses:
        '200':
          description: Антифрод установлен

components:
  schemas:
    Observation:
      type: object
      properties:
        violations:
          type: array
          items:
            enum:
              - remote_control # к пк экзаминуемого подключались по протоколам удалённого рабочего стола
              - clipboard # замечено вставка решения из буфера обмена
              - web # замечено испльзование интернет-ресурсов для поиска ответов
          description: Какие запрещённые действия пользователь совершал. Если указано, значит совершал.
    ObservationUpload:
      type: object
      properties:
        observation:
          $ref: "#/components/schemas/Observation"
        mac:
          type: string
          description: "Message Authentication Code, состоящее из Observation и шифрованного хеша Observation"
  securitySchemes:
    userPassedToken:
      type: http
      scheme: bearer